name=MaxSimpleModbusSlave
version=1.0.0
author=Stephane Raimbault <stephane.raimbault@gmail.com>, Alexandr Kolodkin <alexandr.kolodkin@gmail.com>, Gongola Marko
maintainer=Gongola Marko
sentence=A simple Modbus slave library for Arduino with MAX485 DE/RE control.
paragraph=Arduino Simple Modbus Slave is a ISC licensed library to handle Modbus requests on Arduino (slave).
category=Communication
url=https://github.com/marko55212/Arduino-Simple-Modbus-Slave-for-max485-convertor
architectures=*
